project_id = "hctrnfkowqgcwnotosai"

[functions.cleanup-notifications]
verify_jwt = false

[functions.generate-tickets]
verify_jwt = false

[functions.stripe-webhook]
verify_jwt = false

[functions.subscription-status]
verify_jwt = false
