project_id = "hctrnfkowqgcwnotosai"

[functions.auto-draw]
verify_jwt = false

[functions.cleanup-notifications]
verify_jwt = false

[functions.generate-logo]
verify_jwt = false

[functions.generate-tickets]
verify_jwt = false

[functions.notify-pending-approvals]
verify_jwt = false

[functions.process-ticket-batch]
verify_jwt = false

[functions.send-payment-reminders]
verify_jwt = false

[functions.stripe-webhook]
verify_jwt = false

[functions.subscription-status]
verify_jwt = false
